[watch]

# The time that needs to pass without receiving an alert after which Alertmanager is considered down.
# This should be longer than the repeat_interval set in Alertmanager.
down_interval = "5m"

# The location of the file which stores temporary data for COS Alerter.
data_file = "/run/cos-alerter-data.json"

[notify]

# Destinations are any [Apprise](https://github.com/caronc/apprise) compatible service string.
# See:
# https://github.com/caronc/apprise/wiki/
# https://github.com/caronc/apprise/wiki/Notify_email
destinations = [
  'mailtos://user:pass@domain/?to=example-0@example.com,example-1@example.com',
  'slack://xoxb-1234-1234-4ddbc191d40ee098cbaae6f3523ada2d/#general',
]

# When Alertmanager is down, the amount of time between notifications.
repeat_interval = "1h"
