#!/usr/bin/env python3

import durationpy
import email
import json
import signal
import smtplib
import subprocess
import sys
import time

from alerter import DataWriter, conf, update_conf, send_notifications


def notify(time_data):
    # TODO: actually send email
    if not time.time() - time_data.notify_time > durationpy.from_str(conf['notify']['repeat_interval']).total_seconds():
        #TODO log something here
        return
    time_data.notify_time = time.time()
    print("Alertmanager down! Sending mail.")


def sighup(_, __):
    update_conf()


def send_test_mail(_, __):
    send_notifications(title='COS-Alerter test email.', body='This is a test email automatically generated by COS-alerter.')


def sigint(_, __):
    sys.exit()


def main():

    update_conf()

    # Create the initial data file
    with open(conf['watcher']['data_file'], 'w') as f:
        json.dump({'alert_time': time.time(), 'notify_time': 0.0}, f)

    signal.signal(signal.SIGINT, sigint)
    signal.signal(signal.SIGHUP, sighup)
    signal.signal(signal.SIGUSR1, send_test_mail)

    subprocess.Popen(['flask', '--app', 'root.alerter.server', 'run', '--host', '0.0.0.0'])

    while(True):
        with DataWriter() as time_data:
            if time.time() - time_data.alert_time > durationpy.from_str(conf['watcher']['down_interval']).total_seconds():
                notify(time_data)


if __name__ == '__main__':
    main()
