apiVersion: apps/v1
kind: Deployment
metadata:
  name: cos-alerter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cos-alerter
  template:
    metadata:
      labels:
        app: cos-alerter
    spec:
      containers:
      - name: cos-alerter
        image: <registry-ip>/<image-tag>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/cos-alerter.yaml
          subPath: cos-alerter.yaml
      volumes:
      - name: config
        configMap:
          name: cos-alerter-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cos-alerter-configmap
data:
  cos-alerter.yaml: |
    watch:
      down_interval: "5m"
      wait_for_first_connection: true
      clients: {}
    notify:
      destinations: []
      repeat_interval: "1h"
    log_level: "info"
    web_listen_addr: "0.0.0.0:8080"


