name: Build ROCK

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 * * 0"

jobs:
  build:
    uses: canonical/observability/.github/workflows/build-rock.yaml@main
    secrets: inherit
    with:
      rock-name: cos-alerter
      tag-minor: true
