name: Promote Snap

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable

jobs:
  promote:
    name: Promote Snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo snap install --classic --channel edge snapcraft
          sudo snap install just --classic
      - name: Set from-risk
        env:
          PROMOTE_FROM: ${{ github.event.inputs.promotion }}
        run: |
          case "${PROMOTE_FROM}" in
            "edge -> beta") echo "from_risk=edge" >> "${GITHUB_ENV}" ;;
            "beta -> candidate") echo "from_risk=beta" >> "${GITHUB_ENV}" ;;
            "candidate -> stable") echo "from_risk=candidate" >> "${GITHUB_ENV}" ;;
          esac
      - name: Promote Snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          cd snap
          just promote latest "${from_risk}"
