name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: python3 -m pip install tox
      - name: Run Checks
        run: tox -e lint,static
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: python3 -m pip install tox
      - name: Run Checks
        run: tox -e test,slow-tests
      - name: Upload .coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: .coverage
  coverage:
    name: Coverage
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: python3 -m pip install tox
      - name: Download .coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: Run Checks
        run: tox -e coverage
