name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  tox-checks:
    name: Tox Checks
    needs:
      - ci-ignore
    if: ${{ needs.ci-ignore.outputs.files != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
      - name: Install Dependencies
        run: python3 -m pip install tox
      - name: Run Checks
        run: tox
