#!/usr/bin/env python3

import datetime
import durationpy
import json
import signal
import subprocess
import sys
import textwrap
import time

from .alerter import DataWriter, config, send_notifications


def notify(time_data):
    if not time.time() - time_data.notify_time > durationpy.from_str(config['notify']['repeat_interval']).total_seconds():
        #TODO log something here
        return
    time_data.notify_time = time.time()
    last_alert_time = datetime.datetime.fromtimestamp(time_data.alert_time).strftime('%A, %B %d %Y %I:%M%p %Z')
    title = '**Alertmanager is Down!**'
    body = textwrap.dedent(f'''
        Your Alertmanager instance seems to be down!
        It has not alerted COS-Alerter since {last_alert_time}.
        ''')
    send_notifications(title=title, body=body)


def send_test_mail(_, __):
    send_notifications(title='COS-Alerter test email.', body='This is a test email automatically generated by COS-alerter.')


def sigint(_, __):
    sys.exit()


def main():

    # Create the initial data file
    with open(config['watch']['data_file'], 'w') as f:
        json.dump({'alert_time': time.time(), 'notify_time': 0.0}, f)

    signal.signal(signal.SIGINT, sigint)
    signal.signal(signal.SIGUSR1, send_test_mail)

    subprocess.Popen(['waitress-serve', 'cos_alerter.server:app'])

    while(True):
        with DataWriter() as time_data:
            if time.time() - time_data.alert_time > durationpy.from_str(config['watch']['down_interval']).total_seconds():
                notify(time_data)
        time.sleep(1)


if __name__ == '__main__':
    main()
